<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RazorCompileOnBuild>false</RazorCompileOnBuild>
		<CopyDocumentationFilesFromPackages>true</CopyDocumentationFilesFromPackages>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dynamicweb.Suite" Version="10.*" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.11" />
		<PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.3.0" />
	</ItemGroup>
</Project>
